### ISSUE TITLE
telegram-notify error with text messages having odd number of underscores

### ISSUE THREAD

**Issue by pd321** [NicolasBernaerts/debian-scripts#10]
To test use an example command like one given below which has text having an odd number of underscores
```bash
telegram-notify --success --text 'test_1:beta completed'
```
In my case I recieve the following error
`{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 8"}`

However on changing the text to one which has even number of underscores the error is fixed
```bash
telegram-notify --success --text 'test_1:beta_1 completed'
```

The error could be possibly related to the issue mentioned [here](https://github.com/domoticz/domoticz/issues/3132)

**Comment by NicolasBernaerts** [comment]
Hello,
It must be coming from Telegram markdown syntax where * or _ are used to emphasize things.
In your example, do you have **1:beta** in _italic_ ?

**Comment by pd321** [comment]
Makes sense. In my case the underscores are a part of folder names. I think I should be able to escape all underscores as I am not looking for markdown syntax. The below command behaves as expected for me
```bash
telegram-notify --success --text 'test\_1:beta completed'
```
Thanks for the pointer.
