### ISSUE TITLE
#telegram URL with further info does not work

### ISSUE THREAD

**Issue by wojcikm** [NicolasBernaerts/debian-scripts#13]
https://github.com/NicolasBernaerts/debian-scripts/tree/master/telegram

http://bernaerts.dyndns.org/linux/75-debian/351-debian-send-telegram-notification

**Comment by NicolasBernaerts** [comment]
I changed it to my new site http://www.bernaerts-nicolas.fr/linux/75-debian/351-debian-send-telegram-notification. It should now work ok.
