### ISSUE TITLE
output not formatted correctly

### ISSUE THREAD

**Issue by logicminds** [NicolasBernaerts/debian-scripts#14]
My heroku app is running this script as part of a scheduled job.  This works fine without heroku involved but heroku must be rendering the text differently.

<img width="310" alt="Screen Shot 2020-02-11 at 4 31 11 PM" src="https://user-images.githubusercontent.com/563900/74292471-f420bb00-4cec-11ea-868e-cfa80e26667c.png">

It should look like this:

<img width="339" alt="Screen Shot 2020-02-11 at 4 39 20 PM" src="https://user-images.githubusercontent.com/563900/74292531-1c101e80-4ced-11ea-9f39-731555fef86b.png">

**Comment by NicolasBernaerts** [comment]
Could you please paste the unformatted text you are sending ?
