### ISSUE TITLE
Use Telegram Notify into another script

### ISSUE THREAD

**Issue by AlphaC0de** [NicolasBernaerts/debian-scripts#17]
Is it possible to do something like that? It seems not to work

```
#
# TR_APP_VERSION
# TR_TIME_LOCALTIME
# TR_TORRENT_DIR
# TR_TORRENT_HASH
# TR_TORRENT_ID
# TR_TORRENT_NAME
#

# message title for the notification
title=title"Torrent completed: $TR_TORRENT_NAME"

# the full message text (can use HTML)
message="Download <b>$TR_TORRENT_NAME</b> is completed. <br><br><br>$TR_TIME_LOCALTIME<br>"

echo 'text to be displayed' | /usr/local/sbin/telegram-notify $title $message
```

**Comment by NicolasBernaerts** [comment]
There is some problem in your script.

It should look like this : 

   title="Torrent completed: ${TR_TORRENT_NAME}"
   message="Whatever your HTML message with your ${TR_TORRENT_NAME} ..."
   /usr/local/sbin/telegram-notify --html --title "${title}" --text "${message}"
