### ISSUE TITLE
Telegram Notifier sends path instead of file content.

### ISSUE THREAD

**Issue by D1Ck3n** [NicolasBernaerts/debian-scripts#19]
Good day,

first of all super work that you have done there! The Telegram script runs great!

Unfortunately, I noticed that the server does not give me a log file content, but only the path to the file:

![image](https://user-images.githubusercontent.com/28949322/140077882-8b01ed4b-e2db-4ed0-8bf9-b80428661e92.png)

I used the following command:
`telegram-notify --question --title "Proxmox Disk Health" --text "/var/log/disccheck.log"`

**Comment by marceloabelda** [comment]
Try --file instead of --text

**Comment by D1Ck3n** [comment]
i tried but i'm getting an error:
```# telegram-notify --icon 1F50E --title "Proxmox Disk Health" --file "/var/log/disccheck.txt"
[Info] Using configuration file /etc/telegram-notify.conf
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 41"}```

**Comment by marceloabelda** [comment]
first try with few characters

**Comment by D1Ck3n** [comment]
what do you mean with few characters?

**Comment by NicolasBernaerts** [comment]
It seems there is a problem with underscore character (https://github.com/openhab/openhab-addons/issues/11691).
Do you have such character in your text ?

**Comment by D1Ck3n** [comment]
ok i think i found the issue! i generate a log file with a simple script and the formatting of the print output seems to cause problems:

```
#!/usr/bin/env bash

declare -a mydisks=( $(command ls -1 /dev/ | grep -Ei "^sd[a-z]*$") )

for d in ${mydisks[@]} ; do

ISTGUT=$(command smartctl -H /dev/${d} | grep PASSED | wc -l)
NICHTGUT=$(command smartctl -H /dev/${d} | grep -i failed | wc -l)

if (( ISTGUT != 0 )) ; then
printf " /dev/${d} : $(tput setaf 2)Good$(tput sgr 0)\n"
elif (( NICHTGUT != 0 )) ; then
printf " /dev/${d} : $(tput setaf 1)Replace$(tput sgr 0)\n"
else
printf " /dev/${d} : $(tput setaf 3)Unknown$(tput sgr 0)\n"
fi


done


```

content of the generated file:
```
 /dev/sda : ^[[32mGood^[(B^[[0m
 /dev/sdb : ^[[32mGood^[(B^[[0m
 /dev/sdc : ^[[32mGood^[(B^[[0m
 /dev/sdd : ^[[32mGood^[(B^[[0m
 /dev/sde : ^[[32mGood^[(B^[[0m
```

with plain text it works fine!
