### ISSUE TITLE
Error: Failed to start application: Could not connect to MySQL server.

### ISSUE THREAD

**Issue by cartesien** [NicolasBernaerts/debian-scripts#2]
When i try to cnnect to this page : http://bernaerts.dyndns.org/linux/75-debian/351-debian-send-telegram-notification

i have this error message : 
Error: Failed to start application: Could not connect to MySQL server.

**Comment by NicolasBernaerts** [comment]
Hi, my site had been attacked. Everything is back to normal. Thanks for the notice.
