### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by Radius17** [NicolasBernaerts/debian-scripts#22]
Hi !
I forked telegram folder only for custom use https://github.com/Radius17/Bash-Telegram.
When sending photo or document with title, there is missing --form parse_mode=${DISPLAY_MODE} parameter.
Also "%0A" is not recognizing.
But "\n" works fine in all modes.
So i modified script in my repository like this https://github.com/Radius17/Bash-Telegram/commit/f963122bb033d8622e24f3df4abf90358a571885
May be it will be usefull for you.

Best regards.

**Comment by NicolasBernaerts** [comment]
Thanks Radius17.
I included your patch in the main branch.
