### ISSUE TITLE
adding location?

### ISSUE THREAD

**Issue by z3r0l1nk** [NicolasBernaerts/debian-scripts#24]
Hi,
I'm using your bash script since it appeared.
Is it possible to add location for telegram? 
I want to send location via latitude and longitude .

**Comment by NicolasBernaerts** [comment]
Hi @z3r0l1nk 
I've added --position in v2.4 of the script.
Could you check that it works ok for you ?
Cheers

**Comment by z3r0l1nk** [comment]
Hi @NicolasBernaerts ,

Sorry for the late late response, thank you for the implementation, I confirm that it's working.

Kind regards,
Z3r0L1nk
