### ISSUE TITLE
telegram-notify and ampersand symbol

### ISSUE THREAD

**Issue by jacklul** [NicolasBernaerts/debian-scripts#26]
If you provide "&" in either --title or --text it will cut everything after it.

Scenario 1:
```
telegram-notify --text "Text&ImGone"
```
Results in
```
Text
```

Scenario 2:
```
telegram-notify --text "Text&ImGone" --title "Title"
```
Results in
```
Title

Text
```

Scenario 3:
```
telegram-notify --text "Text&ImGone" --title "Title&ImGoneToo"
```
Results in error:
```
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 0"}
```

Scenario 4:
```
telegram-notify --text "Text&ImGone" --title "Title&ImGoneToo" --html
```
Results in error:
```
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end tag corresponding to start tag \"b\""}
```

**Comment by NicolasBernaerts** [comment]
Have you tried to escape & with \ ?

    telegram-notify --text "Text\&ImGone"

**Comment by jacklul** [comment]
Yes, --text "test\\\&imgone" results in "test\\"

**Comment by jacklul** [comment]
I debugged it and it seems like bash is quoting the text field in single quotes and you cannot escape that character in those.

The only solution that works for me is to replace all & with %26.
No idea if you want to implement it into the script or make the user handle it, perhaps this could be an optional flag or config option.

**Comment by NicolasBernaerts** [comment]
True, & has always been reserved in bash 
Yes, it is better to let users handle it.
