### ISSUE TITLE
[telegram-notify] socks5 support 

### ISSUE THREAD

**Issue by RangerRU** [NicolasBernaerts/debian-scripts#3]
Hello!

Please add support for the socks5 proxy!

Thank you!

**Comment by NicolasBernaerts** [comment]
Hi,
I've added a socks5 server option thru socks-proxy option in configuration file.
Can you check and tell me if it works for you ?
Cheers

**Comment by RangerRU** [comment]
Can you add support for the username and the password for the socks5-server?
