### ISSUE TITLE
debian 9 doesn't display correct icon but \u2705 caracter

### ISSUE THREAD

**Issue by almoondsllc** [NicolasBernaerts/debian-scripts#8]
I think some fonts is missing but which one in debian?
when I send 
echo 'text to be displayed' | telegram-notify --success --text -
I got this
\u2705 text to be displayed
on Telegram

**Comment by atxulo** [comment]
Here's how i've made it work:

Run the command: `locale`. It'll show something like this:
> LANG=C
> LC_CTYPE="C"
> ...

Then, change the locale to UTF-8 and reboot (choose your language):

`sudo update-locale LANG=en_US.UTF-8 LANGUAGE=en.UTF-8`
`sudo reboot`

And now it should work. You can run `locale` again to see the changes

**Comment by NicolasBernaerts** [comment]
Thanks for the tip.
I'll add it in the article.
Cheers
