### ISSUE TITLE
[telegram-notify] Bug for some messages

### ISSUE THREAD

**Issue by therealpeterpython** [NicolasBernaerts/debian-scripts#9]
Hey,
Thank you for your great work!
I am not sure if i found a bug in your telegram-notify script. 
When i use it with the following command `./telegram-notify.sh --user 123456789 --key 987654321:AABBCCDDEEFFGGHHIIJJ --text "test1"` (without a configuration file) i've get the output:
```
[Warning] Configuration file missing /etc/telegram-notify.conf
[Error] Nothing to notify
```

If i run it as `./telegram-notify.sh --user 123456789 --key 987654321:AABBCCDDEEFFGGHHIIJJ --text "test"`
i've get 
```
[Warning] Configuration file missing /etc/telegram-notify.conf
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 16"}
```

It works for all other text inputs i've tried. The same happens when i pipe the texts in.

If its important: i haven't used the installation script but just copied the scipt from github.

**Comment by NicolasBernaerts** [comment]
Hi,

If you give a filename as --text, it will display the content of the file.
Don't you have files named **test** and **test2** in your local directory ?

**Comment by NicolasBernaerts** [comment]
I've added a **--file** option to make it easier.
You can now feed text thru **--text** or **--file**.

**Comment by therealpeterpython** [comment]
Hey,

Seems like i haven't read the manual carefully enough...
I have overseen the fact that --text was for filenames too. Thank you for the fast answer and the clarification with the --file parameter.
